# This file is part of django-environments.
# https://github.com/delgiudices/django-environments

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2016, Luis Del Giudice <luis.dg19@gmail.com>

language: python

python:
    - "2.7"
    - "pypy"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
